-- Montr Database Schema
-- SQLite Schema (compatible with other databases with minor modifications)

-- Media Files Table
-- Stores metadata for uploaded media files (videos and images)
CREATE TABLE IF NOT EXISTS media_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,                    -- Generated unique filename
  original_filename TEXT NOT NULL,           -- Original uploaded filename
  filepath TEXT NOT NULL,                    -- Relative path in storage
  type TEXT NOT NULL CHECK(type IN ('video', 'image')),
  mime_type TEXT,                            -- e.g., video/mp4, image/jpeg
  file_size INTEGER,                         -- Size in bytes
  duration REAL,                             -- Duration in seconds (NULL for images)
  width INTEGER,                             -- Resolution width
  height INTEGER,                            -- Resolution height
  checksum TEXT UNIQUE,                      -- SHA-256 hash for duplicate detection
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Playlists Table
-- Stores playlist information
CREATE TABLE IF NOT EXISTS playlists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Playlist Items Table
-- Junction table linking playlists to media files with ordering
CREATE TABLE IF NOT EXISTS playlist_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  playlist_id INTEGER NOT NULL,
  media_id INTEGER NOT NULL,
  order_index INTEGER NOT NULL,             -- Position in playlist (0-indexed)
  image_duration INTEGER DEFAULT 5,         -- Display duration for images (seconds)
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (media_id) REFERENCES media_files(id) ON DELETE CASCADE,
  UNIQUE(playlist_id, order_index)          -- Ensure unique ordering within playlist
);

-- Clients Table
-- Stores registered client information
CREATE TABLE IF NOT EXISTS clients (
  id TEXT PRIMARY KEY,                       -- UUID generated by client
  name TEXT NOT NULL,                        -- Display name
  assigned_playlist_id INTEGER,              -- Currently assigned playlist
  status TEXT DEFAULT 'offline' CHECK(status IN ('online', 'offline', 'error')),
  last_seen DATETIME,                        -- Last heartbeat timestamp
  version TEXT,                              -- Client version
  capabilities TEXT,                         -- JSON string of capabilities
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assigned_playlist_id) REFERENCES playlists(id) ON DELETE SET NULL
);

-- Client Status Table
-- Stores real-time playback status for clients
CREATE TABLE IF NOT EXISTS client_status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id TEXT NOT NULL,
  current_media_id INTEGER,                  -- Currently playing media
  position REAL,                             -- Playback position in seconds
  is_playing BOOLEAN DEFAULT 0,              -- Playing state
  error_message TEXT,                        -- Last error if any
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  FOREIGN KEY (current_media_id) REFERENCES media_files(id) ON DELETE SET NULL
);

-- System State Table
-- Stores system-wide settings and state
CREATE TABLE IF NOT EXISTS system_state (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance optimization

-- Media files indexes
CREATE INDEX IF NOT EXISTS idx_media_type ON media_files(type);
CREATE INDEX IF NOT EXISTS idx_media_created ON media_files(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_checksum ON media_files(checksum);

-- Playlist items indexes
CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist ON playlist_items(playlist_id, order_index);
CREATE INDEX IF NOT EXISTS idx_playlist_items_media ON playlist_items(media_id);

-- Client indexes
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);
CREATE INDEX IF NOT EXISTS idx_clients_last_seen ON clients(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_clients_playlist ON clients(assigned_playlist_id);

-- Client status indexes
CREATE INDEX IF NOT EXISTS idx_client_status_client ON client_status(client_id);
CREATE INDEX IF NOT EXISTS idx_client_status_timestamp ON client_status(timestamp DESC);

-- Triggers for automatic timestamp updates

-- Update media_files updated_at
CREATE TRIGGER IF NOT EXISTS update_media_files_timestamp
AFTER UPDATE ON media_files
BEGIN
  UPDATE media_files SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Update playlists updated_at
CREATE TRIGGER IF NOT EXISTS update_playlists_timestamp
AFTER UPDATE ON playlists
BEGIN
  UPDATE playlists SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Update playlists timestamp when items change
CREATE TRIGGER IF NOT EXISTS update_playlists_on_item_change
AFTER INSERT ON playlist_items
BEGIN
  UPDATE playlists SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.playlist_id;
END;

CREATE TRIGGER IF NOT EXISTS update_playlists_on_item_update
AFTER UPDATE ON playlist_items
BEGIN
  UPDATE playlists SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.playlist_id;
END;

CREATE TRIGGER IF NOT EXISTS update_playlists_on_item_delete
AFTER DELETE ON playlist_items
BEGIN
  UPDATE playlists SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.playlist_id;
END;

-- Update clients updated_at
CREATE TRIGGER IF NOT EXISTS update_clients_timestamp
AFTER UPDATE ON clients
BEGIN
  UPDATE clients SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Views for common queries

-- View: Playlists with item count
CREATE VIEW IF NOT EXISTS playlists_with_counts AS
SELECT
  p.id,
  p.name,
  p.description,
  COUNT(pi.id) as item_count,
  SUM(CASE
    WHEN mf.type = 'video' THEN COALESCE(mf.duration, 0)
    WHEN mf.type = 'image' THEN COALESCE(pi.image_duration, 5)
    ELSE 0
  END) as total_duration,
  p.created_at,
  p.updated_at
FROM playlists p
LEFT JOIN playlist_items pi ON p.id = pi.playlist_id
LEFT JOIN media_files mf ON pi.media_id = mf.id
GROUP BY p.id;

-- View: Client status with latest update
CREATE VIEW IF NOT EXISTS clients_latest_status AS
SELECT
  c.id,
  c.name,
  c.status,
  c.assigned_playlist_id,
  c.last_seen,
  cs.current_media_id,
  cs.position,
  cs.is_playing,
  cs.error_message,
  cs.timestamp as status_timestamp,
  mf.filename as current_media_filename,
  mf.type as current_media_type,
  p.name as assigned_playlist_name
FROM clients c
LEFT JOIN (
  SELECT DISTINCT client_id,
    FIRST_VALUE(current_media_id) OVER (PARTITION BY client_id ORDER BY timestamp DESC) as current_media_id,
    FIRST_VALUE(position) OVER (PARTITION BY client_id ORDER BY timestamp DESC) as position,
    FIRST_VALUE(is_playing) OVER (PARTITION BY client_id ORDER BY timestamp DESC) as is_playing,
    FIRST_VALUE(error_message) OVER (PARTITION BY client_id ORDER BY timestamp DESC) as error_message,
    FIRST_VALUE(timestamp) OVER (PARTITION BY client_id ORDER BY timestamp DESC) as timestamp
  FROM client_status
) cs ON c.id = cs.client_id
LEFT JOIN media_files mf ON cs.current_media_id = mf.id
LEFT JOIN playlists p ON c.assigned_playlist_id = p.id;

-- View: Media usage statistics
CREATE VIEW IF NOT EXISTS media_usage_stats AS
SELECT
  mf.id,
  mf.filename,
  mf.original_filename,
  mf.type,
  COUNT(DISTINCT pi.playlist_id) as playlist_count,
  COUNT(DISTINCT cs.client_id) as client_playback_count,
  MAX(cs.timestamp) as last_played_at
FROM media_files mf
LEFT JOIN playlist_items pi ON mf.id = pi.media_id
LEFT JOIN client_status cs ON mf.id = cs.current_media_id
GROUP BY mf.id;

-- Insert initial system state
INSERT OR IGNORE INTO system_state (key, value) VALUES ('schema_version', '1.0.0');
INSERT OR IGNORE INTO system_state (key, value) VALUES ('initialized_at', datetime('now'));

-- Comments explaining the schema design

/*
 * Schema Design Notes:
 *
 * 1. Media Files: Central table for all uploaded media
 *    - Checksum used for duplicate detection
 *    - Duration is NULL for images (displayed for configured time)
 *    - Filepath is relative to STORAGE_PATH
 *
 * 2. Playlists & Playlist Items: Many-to-many relationship
 *    - order_index determines playback order
 *    - image_duration overrides default for specific images
 *    - CASCADE delete ensures referential integrity
 *
 * 3. Clients: Registered playback clients
 *    - UUID primary key generated by client
 *    - assigned_playlist_id links to current playlist
 *    - status tracks online/offline/error states
 *    - last_seen updated on heartbeat
 *
 * 4. Client Status: Time-series data of playback state
 *    - New row inserted on each status update
 *    - Can be cleaned up periodically (keep last N days)
 *    - Used for monitoring and analytics
 *
 * 5. System State: Key-value store for system settings
 *    - schema_version for migration tracking
 *    - Can store feature flags, settings, etc.
 *
 * 6. Indexes: Optimized for common query patterns
 *    - Listing media by type or date
 *    - Loading playlist items in order
 *    - Querying client status
 *
 * 7. Triggers: Automatic timestamp management
 *    - updated_at automatically set on UPDATE
 *    - Playlist updated_at changes when items modified
 *
 * 8. Views: Convenient queries for common operations
 *    - Playlist summaries with counts and duration
 *    - Latest client status without joining full history
 *    - Media usage statistics
 */
